### ISSUE TITLE
Error: unparseable date

### ISSUE THREAD

**Issue by GoncaloAlmeidaPTC** [moneymanagerex/android-money-manager-ex#1083]
Since this release that syncing from Dropbox started crashing:

https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2016.11.01.944

The toast message shows something like:

> Erro: unparseable date: "2016-11-01T17:18:47.000Z" (at offset 23)
> Attempting to invoke virtual method "long java.lang.Date.getTime() on a null object reference

Does anybody know how to fix this?

**Comment by MisterY** [comment]
Please try to force download or upload and let me know if the problem persists. 
After moving away from Joda Time, date parsing is done by native Java Date and I'm wondering why is this value being stored.

**Comment by MisterY** [comment]
Full stack trace:
```
Non-fatal Exception: java.text.ParseException: Unparseable date: "2016-11-06T12:13:08.475Z" (at offset 23)
       at java.text.DateFormat.parse(DateFormat.java:555)
       at com.money.manager.ex.utils.MmxDate.from(MmxDate.java:62)
       at com.money.manager.ex.utils.MmxDate.<init>(MmxDate.java:105)
       at com.money.manager.ex.utils.MmxDate.fromIso8601(MmxDate.java:55)
       at com.money.manager.ex.sync.SyncManager.isRemoteFileModified(SyncManager.java:132)
       at com.money.manager.ex.sync.SyncService.triggerSync(SyncService.java:296)
       at com.money.manager.ex.sync.SyncService.onHandleIntent(SyncService.java:157)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```
