### ISSUE TITLE
Background sync service exception on Oreo

### ISSUE THREAD

**Issue by snarchio** [moneymanagerex/android-money-manager-ex#1145]
With android 8 Oreo the background service crashes
I think it is related to the new limitations on background services introduced with Oreo
[https://developer.android.com/about/versions/oreo/background.html#services](https://developer.android.com/about/versions/oreo/background.html#services)
```
09-14 12:33:11.760 8133-8133/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.money.manager.ex, PID: 8133
                                                 java.lang.RuntimeException: Unable to start receiver com.money.manager.ex.sync.SyncBroadcastReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.money.manager.ex.sync.action.SYNC cmp=com.money.manager.ex/.sync.SyncService (has extras) }: app is in background uid UidRecord{d4503e1 u0a249 RCVR idle procs:1 seq(0,0,0)}
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3259)
                                                     at android.app.ActivityThread.-wrap17(Unknown Source:0)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                     at android.os.Looper.loop(Looper.java:164)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                  Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.money.manager.ex.sync.action.SYNC cmp=com.money.manager.ex/.sync.SyncService (has extras) }: app is in background uid UidRecord{d4503e1 u0a249 RCVR idle procs:1 seq(0,0,0)}
                                                     at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
                                                     at android.app.ContextImpl.startService(ContextImpl.java:1461)
                                                     at android.content.ContextWrapper.startService(ContextWrapper.java:644)
                                                     at android.content.ContextWrapper.startService(ContextWrapper.java:644)
                                                     at com.money.manager.ex.sync.SyncBroadcastReceiver.onReceive(SyncBroadcastReceiver.java:53)
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3252)
                                                     at android.app.ActivityThread.-wrap17(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by MisterY** [comment]
Thanks. This might serve as a push to move to Android Sync Framework #950.

**Comment by MisterY** [comment]
As a temporary solution, we need to use [JobScheduler](https://developer.android.com/reference/android/app/job/JobScheduler.html).

**Comment by MisterY** [comment]
Unfortunately, I can not run Android 8 on any emulator and can not confirm whether the fixes work. Looking for a volunteer.

**Comment by snarchio** [comment]
I tested both with an emulator and a phone and i get
```
10-24 09:04:47.225 4511-4511/? E/AndroidRuntime: FATAL EXCEPTION: main 
    Process: com.money.manager.ex.debug, PID: 4511
    android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1775)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```
This is stated in the documentation
>  For this reason, Android 8.0 introduces the new method startForegroundService() to start a new service in the foreground. After the system has created the service, the app has five seconds to call the service's startForeground() method to show the new service's user-visible notification. If the app does not call startForeground() within the time limit, the system stops the service and declares the app to be ANR

I think the best approach is to use the new method in support library [JobIntentService](https://developer.android.com/reference/android/support/v4/app/JobIntentService.html)

**Comment by MisterY** [comment]
Thanks! I have to work out what's going on with my emulator.
OK, I will try to add the call to .startForeground(). Hopefully this works. 
Otherwise, it would be better to use the task library listed above. That way we'd be backwards compatible with all existing devices.

**Comment by MisterY** [comment]
New Beta version just released. Volunteers with Android 8, please have a go and report back if you see any issues. Sync notifications don't seem to work in O.

**Comment by snarchio** [comment]
I installed the beta
i see some
`E/NotificationService: No Channel found for pkg=com.money.manager.ex.beta, channelId=null, id=1, tag=null, opPkg=com.money.manager.ex.beta, callingUid=10019, userId=0, incomingUserId=0, notificationUid=10019, notification=Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0xff607d8b vis=PRIVATE)
`
And also
`E/AndroidRuntime: FATAL EXCEPTION: main
  Process: com.money.manager.ex.beta, PID: 1614
  java.lang.RuntimeException: Unable to start receiver com.money.manager.ex.sync.SyncBroadcastReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.money.manager.ex.sync.action.SYNC cmp=com.money.manager.ex.beta/com.money.manager.ex.sync.SyncService (has extras) }: app is in background uid UidRecord{c5604c7 u0a19 RCVR bg:+11m29s160ms idle procs:1 seq(0,0,0)}`

Seems you are not referencing the _beta_ BroadcastReceiver

**Comment by MisterY** [comment]
As this will require a significant rewrite of quite a few parts of application, the recommended workaround is not to upgrade to Android 8 for the moment. Sorry.

**Comment by MisterY** [comment]
Finally I had some time over the holidays to look a bit into this.
I think I have resolved the core problem. Any feedback is much appreciated as I can only test in an emulator.

**Comment by snarchio** [comment]
After some days using it on Android 8.1 I confirm that works fine
Thanks

**Comment by MisterY** [comment]
Thanks for the confirmation. Now we can have a stable release for the New Year's. :)

**Comment by paulpv** [comment]
Be careful: https://issuetracker.google.com/issues/76112072

**Comment by MisterY** [comment]
Yep, @paulpv, I think I removed these calls to Foreground service and am using another approach, which was simpler. There is a compatibility class that is almost a 1-to-1 replacement for the previous job manager.

**Comment by raphaelbgr** [comment]
@MisterY tell us about what you used, I'm facing the exact same problem.

**Comment by MisterY** [comment]
Uh, it's been a while... Check [this](https://github.com/moneymanagerex/android-money-manager-ex/commit/a7cfdee3310ad17b6ae6323bd9b8aed0a837ff37) and [this](https://github.com/moneymanagerex/android-money-manager-ex/commit/2e1c9bf147330ce8f00850918480a8c6010a733b) for implementation.
I think they added some wrapper in the newer Support Library that made the transition easier.
