### ISSUE TITLE
JellyBean: crash when listing account transactions the second time

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#120]
scenario: from the main list,

- tap account to open the list of transactions,
- open drawer
- tap Home
- tap the same account

The app crashes here on JellyBean. Can anything be done to prevent this?
The cause is in onActivityCreated, 

    if (mListHeader != null) getListView().addHeaderView(mListHeader);

**Comment by AlessandroLazzari** [comment]
It was reported by some user? Or does this problem have you simulated you?
The problem seems to me to be random, have you also verified this behavior?

**Comment by AlessandroLazzari** [comment]
Can you post you logcat?

**Comment by MisterY** [comment]
Happens to me in the emulator. I'll copy the exception.

**Comment by MisterY** [comment]
04-08 17:02:54.629    1597-1597/com.money.manager.ex E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IllegalStateException: Cannot add header view to list -- setAdapter has already been called.
            at android.widget.ListView.addHeaderView(ListView.java:255)
            at android.widget.ListView.addHeaderView(ListView.java:284)
            at com.money.manager.ex.fragment.AllDataFragment.onActivityCreated(AllDataFragment.java:204)
            at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1794)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:977)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1136)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1118)
            at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1927)
            at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1800)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:977)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1136)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1499)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:456)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by AlessandroLazzari** [comment]
Thanks a lot tonight, I hope, I will fix this bug.

**Comment by MisterY** [comment]
Thanks! Can you also check and merge my pull request? I need the delete function for testing the functionality for entering recurring split transactions. While testing, I'm creating lots of records that need to be deleted.

**Comment by AlessandroLazzari** [comment]
Sure!
