### ISSUE TITLE
Reports drill down 'Error: Attempt to invoke virtual method 'int.java.lang.integer.intValue()'

### ISSUE THREAD

**Issue by ghost** [moneymanagerex/android-money-manager-ex#1213]
Phone: Google Pixel 2XL
OS: Latest February patch 8.1.0
MMEX version: 2/26/18 Release (happened prior to this release also)
Screenshot: Attached

Reproduce: Options Triple Bar (upper left of screen), Choose reports, Choose (payees, or where the money goes, or where the money comes from, or categories), Touch an entry which I assume is supposed to drill into.  Any entry will show the error: Error: Attempt to invoke virtual method 'int.java.lang.integer.intValue()' on a null object reference.

To be honest I didn't even think of having the drill down feature in the mobile version and found it by accident.  If this feature doesn't exist maybe you could suppress the error.  Working would be nice but realize the developers time constraints.
<img src="https://user-images.githubusercontent.com/34166578/36675916-e4ed6f76-1acf-11e8-9b0b-f8ce759e3d66.jpg" width="200px"/>

**Comment by MisterY** [comment]
That's strange. I can drill down and get the list of underlying transactions for each option selected.

**Comment by bluehelo** [comment]
Might be on my end.  Ran the db integrity check and came back ok.  Ran the db schema and received the warning below:
![screenshot_20180226-094920](https://user-images.githubusercontent.com/34166578/36680368-3a725604-1adb-11e8-9f89-cc8f3e1db900.png)

I will export the data later and start with a new db, then re-import.  I will update within the next 24 hours.

**Comment by AC-T** [comment]
I'm seeing this as well - Nexus 5x Oreo 8.1.0, MMEX 2018.02.26 981-beta.  Using MMEX 1.3.3 (DB v.7) on Windows 10/Mac Sierra.

Running check Schema, I get the Error about tables missing but also:

Table missing:  SPLITTRANSACTIONS_V2

I do have developer options turned on.

Regards,

Art

**Comment by MisterY** [comment]
> Table missing: SPLITTRANSACTIONS_V2
I don't have that table either so this should not be the cause.
Just checked the crash logs. This seems to fit the bill:
```
Fatal Exception: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.database.CursorWindow.nativeGetString(CursorWindow.java)
       at android.database.CursorWindow.getString(CursorWindow.java:438)
       at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
       at android.database.CursorWrapper.getString(CursorWrapper.java:137)
       at com.money.manager.ex.reports.PayeeReportAdapter.bindView(PayeeReportAdapter.java:55)
       at android.support.v4.widget.CursorAdapter.getView(CursorAdapter.java:273)
       at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
       at android.widget.AbsListView.obtainView(AbsListView.java:2365)
       at android.widget.ListView.makeAndAddView(ListView.java:2052)
       at android.widget.ListView.fillDown(ListView.java:786)
       at android.widget.ListView.fillFromTop(ListView.java:847)
       at android.widget.ListView.layoutChildren(ListView.java:1798)
       at android.widget.AbsListView.onLayout(AbsListView.java:2164)
       at android.view.View.layout(View.java:19659)
       at android.view.ViewGroup.layout(ViewGroup.java:6075)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19659)
       at android.view.ViewGroup.layout(ViewGroup.java:6075)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19659)
       at android.view.ViewGroup.layout(ViewGroup.java:6075)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:19659)
       at android.view.ViewGroup.layout(ViewGroup.java:6075)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:19659)
       at android.view.ViewGroup.layout(ViewGroup.java:6075)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19659)
       at android.view.ViewGroup.layout(ViewGroup.java:6075)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:19659)
       at android.view.ViewGroup.layout(ViewGroup.java:6075)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19659)
       at android.view.ViewGroup.layout(ViewGroup.java:6075)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:19659)
       at android.view.ViewGroup.layout(ViewGroup.java:6075)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
       at android.view.View.layout(View.java:19659)
       at android.view.ViewGroup.layout(ViewGroup.java:6075)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:658)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by AC-T** [comment]
"_Which exact report(s) do you get the error on?_"

I get the error when tapping on a category in the following reports:
- Where the money goes
- Where the money comes from
- Category report

I do not get an error when tapping on a month in the Income and Expenses report - in that case, tapping on a month brings up a list of transactions.

Also, tapping on the Payee report crashes the app.

Art

**Comment by Li0n13** [comment]
Phone: Xiaomi Redmi Note 5
OS: 8.1.0
MMEX version: 2018.02.26.981

I have the same error. Running "check schema", I got error "tables missing in the database".

Using "sqldiff" tool from https://www.sqlite.org/2018/sqlite-tools-win32-x86-3250300.zip, I got difference between my database and the new created with script https://github.com/moneymanagerex/android-money-manager-ex/blob/master/app/src/main/res/raw/tables_v1.sql.

After applying differences I run "check schema" and got message "db_check_schema_success". But I still have _"Error: Attempt to invoke virtual method 'int.java.lang.integer.intValue()"_.

**Comment by vladimir-poleh** [comment]
I have same problem on the OnePlus 5.

I have tried to debug this issue and have found that it is problem with the characters case - columns names in the cursor are not the same as expected (for example ```SubCategID``` instead of ```SubcategID```). It seems to be an issue of the ```query_mobiledata.sql```.

Will try to fix it.

**Comment by wolfsolver** [comment]
Give a try to latest 202401 release series.
