### ISSUE TITLE
App crashed when I opened  the data base and tried to upload a non MMB file

### ISSUE THREAD

**Issue by cckole** [moneymanagerex/android-money-manager-ex#1359]
***App version***: Version. 2019.04.10.1000-beta(1000)
### Description

App crashed when I opened data base and wanted to upload an image.

### Expected behavior

I should be able to upload image when I opened the data base and clicked on other.

### Steps to reproduce

- Launch the app
- Click on the menu button BG the top left side
- Click on data base
- Click on other and select an image. The app will crash.

### Reproducing the behaviour

https://youtu.be/a1txwhA-BIM

Device used: Android 7.0 Techno spark K7

``` FATAL EXCEPTION: main
05-08 09:15:48.412  9117  9117 E AndroidRuntime: Process: com.money.manager.ex, PID: 9117
05-08 09:15:48.412  9117  9117 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=15, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:5309 flg=0x43 }} to activity {com.money.manager.ex/com.money.manager.ex.home.MainActivity}: java.lang.IllegalArgumentException: Not a valid database file!
05-08 09:15:48.412  9117  9117 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4178)
05-08 09:15:48.412  9117  9117 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4221)
05-08 09:15:48.412  9117  9117 E AndroidRuntime: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
05-08 09:15:48.412  9117  9117 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1583)
05-08 09:15:48.412  9117  9117 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
05-08 09:15:48.412  9117  9117 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
05-08 09:15:48.412  9117  9117 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6251)
05-08 09:15:48.412  9117  9117 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-08 09:15:48.412  9117  9117 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
05-08 09:15:48.412  9117  9117 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
05-08 09:15:48.412  9117  9117 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Not a valid database file!
05-08 09:15:48.412  9117  9117 E AndroidRuntime: 	at com.money.manager.ex.utils.MmxDatabaseUtils.useDatabase(MmxDatabaseUtils.java:207)
05-08 09:15:48.412  9117  9117 E AndroidRuntime: 	at com.money.manager.ex.core.docstorage.FileStorageHelper.pullDatabase(FileStorageHelper.java:207)
05-08 09:15:48.412  9117  9117 E AndroidRuntime: 	at com.money.manager.ex.core.docstorage.FileStorageHelper.selectDatabase(FileStorageHelper.java:92)
05-08 09:15:48.412  9117  9117 E AndroidRuntime: 	at com.money.manager.ex.home.MainActivity.onActivityResult(MainActivity.java:318)
05-08 09:15:48.412  9117  9117 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6928)
05-08 09:15:48.412  9117  9117 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4174)
05-08 09:15:48.412  9117  9117 E AndroidRuntime: 	... 9 more```

**Comment by wolfsolver** [comment]
Still present in 2024.01.05

This is a minor issue.

**Comment by wolfsolver** [comment]
Not sure regarding the fix..
@guanlisheng can be somethings like
FileStorageHelper.java line 202 replace 
`        dbUtils.useDatabase(metadata);`
with
`
        try {
              dbUtils.useDatabase(metadata);
        } catch (Exception e) {
            Timber.e("Not Valid mmb file");
            return;
        }
`
