### ISSUE TITLE
Adding a Payee forces App back to homepage

### ISSUE THREAD

**Issue by WangGuox1n** [moneymanagerex/android-money-manager-ex#1371]
Hi, I developed an automatic-testing tool and it detected these exceptions in your app(version 2018.11.15.987). I would like to know if you consider them as bug?
Device Information: android 4.4, Genymotion Custom Phone.

after I add a new payee, the App back to homepage instead of staying in Payees page.

And there are some exception information when I testing the app.
```
E/WindowManager(29522): android.view.WindowLeaked: Activity com.money.manager.ex.PayeeActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{52a29350 V.E..... R....... 0,0-729,441} that was originally added here
E/WindowManager(29522): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
E/WindowManager(29522): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
E/WindowManager(29522): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
E/WindowManager(29522): 	at android.app.Dialog.show(Dialog.java:286)
E/WindowManager(29522): 	at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:1350)
E/WindowManager(29522): 	at com.money.manager.ex.fragment.PayeeListFragment.showDialogEditPayeeName(PayeeListFragment.java:435)
E/WindowManager(29522): 	at com.money.manager.ex.fragment.PayeeListFragment.onFloatingActionButtonClicked(PayeeListFragment.java:446)
E/WindowManager(29522): 	at com.money.manager.ex.common.BaseListFragment$2.onClick(BaseListFragment.java:245)
E/WindowManager(29522): 	at android.view.View.performClick(View.java:4438)
E/WindowManager(29522): 	at android.view.View$PerformClick.run(View.java:18422)
E/WindowManager(29522): 	at android.os.Handler.handleCallback(Handler.java:733)
E/WindowManager(29522): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/WindowManager(29522): 	at android.os.Looper.loop(Looper.java:136)
E/WindowManager(29522): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/WindowManager(29522): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/WindowManager(29522): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/WindowManager(29522): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/WindowManager(29522): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/WindowManager(29522): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by WangGuox1n** [comment]
```
E/AndroidRuntime(21737): FATAL EXCEPTION: main
E/AndroidRuntime(21737): Process: com.money.manager.ex, PID: 21737
E/AndroidRuntime(21737): java.lang.NullPointerException
E/AndroidRuntime(21737): 	at com.money.manager.ex.investment.InvestmentTransactionEditActivity.onCommissionClick(InvestmentTransactionEditActivity.java:237)
E/AndroidRuntime(21737): 	at com.money.manager.ex.investment.InvestmentTransactionEditActivity_ViewBinding$3.doClick(InvestmentTransactionEditActivity_ViewBinding.java:57)
E/AndroidRuntime(21737): 	at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
E/AndroidRuntime(21737): 	at android.view.View.performClick(View.java:4438)
E/AndroidRuntime(21737): 	at android.view.View$PerformClick.run(View.java:18422)
E/AndroidRuntime(21737): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(21737): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(21737): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(21737): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(21737): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(21737): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(21737): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(21737): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(21737): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by wolfsolver** [comment]
Seems ok in 2023.13.27.

I think can be closed
