### ISSUE TITLE
window leak in CalculatorActivity

### ISSUE THREAD

**Issue by anlalalu** [moneymanagerex/android-money-manager-ex#1382]
###### Reproduction Steps

1. tap 'create new account'
2. edit initial balance
3. long click save and a dialog 'Save' appears
4. click '=' when the dialog exists

###### Stack Trace

E/WindowManager: android.view.WindowLeaked: Activity com.money.manager.ex.common.CalculatorActivity has leaked window android.widget.LinearLayout{52a65634 V.E..... ......I. 0,0-157,96} that was originally added here
                                                    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
                                                    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
                                                    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                    at androidx.appcompat.widget.TooltipPopup.show(TooltipPopup.java:86)
                                                    at androidx.appcompat.widget.TooltipCompatHandler.show(TooltipCompatHandler.java:174)
                                                    at androidx.appcompat.widget.TooltipCompatHandler.onLongClick(TooltipCompatHandler.java:123)
                                                    at android.view.View.performLongClick(View.java:4474)
                                                    at android.widget.TextView.performLongClick(TextView.java:8357)
                                                    at android.view.View$CheckForLongPress.run(View.java:18401)
                                                    at android.os.Handler.handleCallback(Handler.java:733)
                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                    at android.os.Looper.loop(Looper.java:136)
                                                    at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                    at dalvik.system.NativeStart.main(Native Method)

###### Debug info
App Version = 2019.02.14.994

Android Version = 4.4.4

maybe can be solved like this: https://stackoverflow.com/questions/2850573/activity-has-leaked-window-that-was-originally-added

###### Reproduction Steps

1. open sidebar
2. tap 'search'
3. long click 'search' a dialog appears
4. press 'back'

###### Reproduction Steps

1. open sidebar
2. tap 'Reports'
3. tap 'Income Vs Expenses'
4. long click 'show charts'
5. press back

###### Reproduction Steps

1. long click 'search' in home interface
2. rotate the screen

###### Reproduction Steps

1. open side bar
2. tap 'categories'
3. tap 'add'
4. rotate the screen

**Comment by anlalalu** [comment]
This can also be reproduced in Android 7.1.0 do you consider it as a defect?
