### ISSUE TITLE
window leak in PayeeActivity

### ISSUE THREAD

**Issue by anlalalu** [moneymanagerex/android-money-manager-ex#1383]
###### Reproduction Steps

1. open sidebar
2. tap 'search'
3. tap 'select payee'
4. tap 'add'
5. rotate the screen

###### Stack Trace

E/WindowManager: android.view.WindowLeaked: Activity com.money.manager.ex.PayeeActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{529e8bfc V.E..... R....... 0,0-729,441} that was originally added here
                                                    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
                                                    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
                                                    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                    at android.app.Dialog.show(Dialog.java:286)
                                                    at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:1350)
                                                    at com.money.manager.ex.fragment.PayeeListFragment.showDialogEditPayeeName(PayeeListFragment.java:435)
                                                    at com.money.manager.ex.fragment.PayeeListFragment.onFloatingActionButtonClicked(PayeeListFragment.java:446)
                                                    at com.money.manager.ex.common.BaseListFragment$2.onClick(BaseListFragment.java:247)
                                                    at android.view.View.performClick(View.java:4438)
                                                    at android.view.View$PerformClick.run(View.java:18422)
                                                    at android.os.Handler.handleCallback(Handler.java:733)
                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                    at android.os.Looper.loop(Looper.java:136)
                                                    at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                    at dalvik.system.NativeStart.main(Native Method)

###### Debug info
App Version = 2019.02.14.994

Android Version = 4.4.4

**Comment by anlalalu** [comment]
This may be solved with reference to this: maybe can be solved like this: https://stackoverflow.com/questions/2850573/activity-has-leaked-window-that-was-originally-added.

Do you consider it as a defect?

**Comment by luisdev** [comment]
I can't reproduce this problem on my Samsung S22 Ultra with build 2023.12.27 (1007).
