### ISSUE TITLE
crash when activating passcode

### ISSUE THREAD

**Issue by anlalalu** [moneymanagerex/android-money-manager-ex#1384]
###### Reproduction Steps

1. open sidebar
2. tap 'settings'
3. tap 'security'
4. tap 'activate passcode'

###### Stack Trace

E/dalvikvm: Could not find class 'android.security.keystore.KeyGenParameterSpec$Builder', referenced from method com.money.manager.ex.PasscodeActivity.generateKey
E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.money.manager.ex.debug, PID: 1306
                                                 java.lang.VerifyError: com/money/manager/ex/PasscodeActivity
                                                     at java.lang.Class.newInstanceImpl(Native Method)
                                                     at java.lang.Class.newInstance(Class.java:1208)
                                                     at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2101)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)

###### Debug info
App Version = 2019.02.14.994

Android Version = 4.4.4

**Comment by olibac** [comment]
Same error here.

App Version: 219.02.14.994-release
Android Version: 8.1.0

**Comment by olibac** [comment]
@anlalalu where can I get the StackTrace? As my Android version is 8.1.0 maybe the exception is not the same.
