### ISSUE TITLE
Crash when trying to add a transaction

### ISSUE THREAD

**Issue by Zeit08** [moneymanagerex/android-money-manager-ex#1460]
When I try to tap the plus button, I get a crash, here's the android log

````
type: crash
osVersion: google/bluejay/bluejay:14/UP1A.231105.003/2023112900:user/release-keys
package: com.money.manager.ex:1002
process: com.money.manager.ex
processUptime: 3089 + 192 ms
installer: com.android.packageinstaller

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.money.manager.ex/com.money.manager.ex.transactions.CheckingTransactionEditActivity}: java.lang.IllegalArgumentException: Illegal pattern character 'o'
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3793)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3933)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.IllegalArgumentException: Illegal pattern character 'o'
	at java.text.SimpleDateFormat.compile(SimpleDateFormat.java:953)
	at java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:739)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:710)
	at com.money.manager.ex.utils.MmxDateTimeUtils.getFormatterFor(MmxDateTimeUtils.java:210)
	at com.money.manager.ex.utils.MmxDateTimeUtils.format(MmxDateTimeUtils.java:72)
	at com.money.manager.ex.transactions.EditTransactionCommonFunctions.showDate(EditTransactionCommonFunctions.java:1441)
	at com.money.manager.ex.transactions.EditTransactionCommonFunctions.initDateSelector(EditTransactionCommonFunctions.java:470)
	at com.money.manager.ex.transactions.CheckingTransactionEditActivity.initializeInputControls(CheckingTransactionEditActivity.java:356)
	at com.money.manager.ex.transactions.CheckingTransactionEditActivity.onCreate(CheckingTransactionEditActivity.java:121)
	at android.app.Activity.performCreate(Activity.java:8651)
	at android.app.Activity.performCreate(Activity.java:8629)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1461)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3775)
	... 14 more

````

The opened database was from mmex for Linux v.1.6.4 and I noticed they had different db versions maybe?

**Comment by guanlisheng** [comment]
hi @Zeit08 , thanks for reporting the issue.

from the tracing log, I guess it was cased by your date format.  would you try an ISO date format?

**Comment by luisdev** [comment]
> from the tracing log, I guess it was caused by your date format. would you try an ISO date format?

Shouldn't some error handling be added to avoid this, so that if you don't have a valid date setting, MMX pops up a message with an instructon for you to check your date settings?

**Comment by guanlisheng** [comment]
hi @luisdev, this would be a followup
