### ISSUE TITLE
Crash when share transaction list 

### ISSUE THREAD

**Issue by wolfsolver** [moneymanagerex/android-money-manager-ex#1518]
**Describe the bug**
In transaction list (Home --> search --> go, see picture 1 below), sharing list cause a crash:

from logcat
```
01-13 22:01:21.833  8743  8743 E QifExport: .qif export
01-13 22:01:21.833  8743  8743 E QifExport: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
01-13 22:01:21.833  8743  8743 E QifExport: at com.money.manager.ex.viewmodels.AccountTransactionDisplay.getIsSplit(AccountTransactionDisplay.java:88)
01-13 22:01:21.833  8743  8743 E QifExport: at com.money.manager.ex.servicelayer.qif.QifRecord.parse(QifRecord.java:119)
01-13 22:01:21.833  8743  8743 E QifExport: at com.money.manager.ex.servicelayer.qif.QifGenerator.createFromAdapter(QifGenerator.java:72)
01-13 22:01:21.833  8743  8743 E QifExport: at com.money.manager.ex.servicelayer.qif.QifExport.export_internal(QifExport.java:62)
01-13 22:01:21.833  8743  8743 E QifExport: at com.money.manager.ex.servicelayer.qif.QifExport.export(QifExport.java:48)
```

Taking a look to code I notice that in `int split = getInt(QueryAllData.SPLITTED);` value of QueryAllData.SPLITTED is "Splitted", while in nMap (see in debug) has "SPLITTED"

<img width="649" alt="image" src="https://github.com/moneymanagerex/android-money-manager-ex/assets/3205448/0ed54d2e-31f4-47a0-b264-b8e4cd14409f">

How can I fix it? Alling SPLITTED to lowercase in nMap or more simple set Splitted to Uppercase in QueryAllData.SPLITTED Definition?

Just a note. Set     `public static final String SPLITTED = "SPLITTED";` resolve the issue. 

**Picture 1**
<img width="162" alt="image" src="https://github.com/moneymanagerex/android-money-manager-ex/assets/3205448/c4f5a036-8791-4e49-b5fe-c9121bb9c535">

**Comment by wolfsolver** [comment]
fixed in next release
