### ISSUE TITLE
Crash on income/expenses 

### ISSUE THREAD

**Issue by wolfsolver** [moneymanagerex/android-money-manager-ex#1546]
**Describe the bug**
2024.01 series crash if open report income/expence

ToDo: 
- [ ] get logcat for analysis

**Comment by luisdev** [comment]
I can reproduce the app crash issue when I open the "Income & Expenses" report from the Reports menu in 2024.01.23 (1016).

**Comment by wolfsolver** [comment]
Deep analisys show regression error on merge #1540 
fixed in next pull request 

<details>
<summary>Dump</summary>

```
FATAL EXCEPTION: main
Process: com.money.manager.ex, PID: 4570
android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 4
	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:521)
	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:139)
	at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:71)
	at android.database.CursorWrapper.getInt(CursorWrapper.java:126)
	at com.money.manager.ex.reports.IncomeVsExpensesListFragment.onLoadFinished(IncomeVsExpensesListFragment.java:203)
	at com.money.manager.ex.reports.IncomeVsExpensesListFragment.onLoadFinished(IncomeVsExpensesListFragment.java:68)
	at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:250)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:189)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:174)
	at androidx.loader.content.Loader.deliverResult(Loader.java:132)
	at androidx.loader.content.CursorLoader.deliverResult(CursorLoader.java:109)
	at androidx.loader.content.CursorLoader.deliverResult(CursorLoader.java:41)
	at androidx.loader.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:258)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:83)
	at androidx.loader.content.ModernAsyncTask.finish(ModernAsyncTask.java:490)
	at androidx.loader.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:507)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

```

</detail>

Need to be analized that data object as Column
