### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by wolfsolver** [moneymanagerex/android-money-manager-ex#1567]
**Describe the bug**
Crash on startup

**To Reproduce**
Only occurs on first startup (after reboot or after force close)

**Device Information:**
 - Device: Motorola G100
 - OS: Android 12
 - Cloud Storage: onedrive
 - App Version: 2024.02.08

**Additional context**
<details><summary>LogCat</summary>
FATAL EXCEPTION: AsyncTask #1
Process: com.money.manager.ex, PID: 31063
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: Attempt to read from field 'com.money.manager.ex.utils.MmxDate com.money.manager.ex.core.docstorage.DocFileMetadata.lastModified' on a null object reference in method 'boolean com.money.manager.ex.core.docstorage.FileStorageHelper.isRemoteFileChanged(com.money.manager.ex.home.DatabaseMetadata)'
	at com.money.manager.ex.core.docstorage.FileStorageHelper.isRemoteFileChanged(FileStorageHelper.java:175)
	at com.money.manager.ex.sync.SyncService.triggerSync(SyncService.java:274)
	at com.money.manager.ex.sync.SyncService.onHandleWork(SyncService.java:139)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:396)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
	at java.lang.Thread.run(Thread.java:1012) 
</details>

**Comment by wolfsolver** [comment]
**root cause analisys**
FileStorageHelper
  isRemoteFileChanged
    metadata.localpath = "/storage/emulated/0/Android/data/com.money.manager.ex/files/databases/2024-ContiEmmanuele.mmb"
    metadata.remotepath = "content://com.microsoft.skydrive.content.StorageAccessProvider/document/content%3A%2F%2Fcom.microsoft.skydrive.content.metadata%2FDrive%2FRID%2F_[omissis]_%2540outlook.it%2FItem%2FRID%_[omissis]_%2FProperty%2F%3FRefreshOption%3DAutoRefresh%26RefreshTimeOut%3D15000%26CostAttributionKey%3D11-21-1"
    metadata.localSnapshotTime = 2024-02-09T19:43:53.602+0100
    metadata.remotelastcangedate = 2024-02-09T19:43:59.600+0100
    remoteModified = Fri Feb 09 19:43:59 GMT+01:00 2024
  remote is null

getRemoteMetadata
  remoteUri = content://com.microsoft.skydrive.content.StorageAccessProvider/document/content%3A%2F%2Fcom.microsoft.skydrive.content.metadata%2FDrive%2FRID%2F_[omissis]_%2540outlook.it%2FItem%2FRID%_[omissis]_%2FProperty%2F%3FRefreshOption%3DAutoRefresh%26RefreshTimeOut%3D15000%26CostAttributionKey%3D11-21-1

at line 303 cursos is null
