### ISSUE TITLE
RTL layout

### ISSUE THREAD

**Issue by islam2hamy** [moneymanagerex/android-money-manager-ex#1650]
**Describe the bug**
All layout not in RTL

**To Reproduce**
1. Change phone language to any RTL language (ex. Arabic)
2. Open the app

**Expected behavior**
all app windows , colums ,etc , will appear from right to left

**Device Information:**
- Device: Redmi note 12
- OS: Android 14
- Storage: Phone storage
- Synchronization: Enabled - never
- Encrypted: no
- App Version: 2024.04.01

**Comment by islam2hamy** [comment]
Hello @guanlisheng ,
app crach

> FATAL EXCEPTION: main
Process: com.money.manager.ex, PID: 6365
android.view.InflateException: Binary XML file line #50 in com.money.manager.ex:layout/fragment_tutorial_accounts: Binary XML file line #50 in com.money.manager.ex:layout/fragment_tutorial_accounts: Error inflating class com.caverock.androidsvg.SVGImageView
Caused by: android.view.InflateException: Binary XML file line #50 in com.money.manager.ex:layout/fragment_tutorial_accounts: Error inflating class com.caverock.androidsvg.SVGImageView
Caused by: java.lang.ClassNotFoundException: com.caverock.androidsvg.SVGImageView
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:536)
	at android.view.LayoutInflater.createView(LayoutInflater.java:840)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1031)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:986)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1148)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1109)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1151)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1109)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:707)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:545)
	at com.money.manager.ex.tutorial.TutorialAccountsFragment.onCreateView(TutorialAccountsFragment.java:47)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1901)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1819)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1731)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
	at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:274)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
	at android.view.View.measure(View.java:27989)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:27989)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:1031)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27989)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27989)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27989)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:813)
	at android.view.View.measure(View.java:27989)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4734)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3252)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3608)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2950)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10238)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1634)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1643)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1172)
	at android.view.Choreographer.doFrame(Choreographer.java:1076)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1607)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8727)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.ClassNotFoundException: com.caverock.androidsvg.SVGImageView
	... 60 more

**Comment by guanlisheng** [comment]
hey @islam2hamy 

Just updated the latest packages in place, can you have a retry?

**Comment by islam2hamy** [comment]
Hello @guanlisheng 

Remove f-droid v. , install github v.
Both 15 and 16 apk

**Comment by islam2hamy** [comment]
Hello @guanlisheng 
it is work with v.21.4.2024
