### ISSUE TITLE
app crash when user inserti new transactions

### ISSUE THREAD

**Issue by AlessandroLazzari** [moneymanagerex/android-money-manager-ex#205]
This is logcat:
 java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
at com.money.manager.ex.CheckingAccountActivity.removeAllSplitCategories(CheckingAccountActivity.java:299)
at com.money.manager.ex.CheckingAccountActivity.updateData(CheckingAccountActivity.java:1339)
at com.money.manager.ex.CheckingAccountActivity.onActionDoneClick(CheckingAccountActivity.java:940)
at com.money.manager.ex.fragment.BaseFragmentActivity$4.onClick(BaseFragmentActivity.java:163)
at android.view.View.performClick(View.java:5218)
at android.view.View$PerformClick.run(View.java:20968)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6066)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

**Comment by MisterY** [comment]
This was fixed and merged yesterday. A new Beta release would be great, along with the current merge requests, so that beta testers can find issues like this.
Ciao

**Comment by MisterY** [comment]
#198
