### ISSUE TITLE
Switching to Previous Month in Categories report shows Error Parsing Date

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#482]
Try with different locale (Russian).

> E/unknown ( 4925): Error parsing date: Unparseable date: "2015-08-01" (at offset 4)
W/System.err( 4925): java.text.ParseException: Unparseable date: "2015-08-01" (at offset 4)
W/System.err( 4925): at java.text.DateFormat.parse(DateFormat.java:555)
W/System.err( 4925): at com.money.manager.ex.utils.DateUtils.getDateFromString(DateUtils.java:81)
W/System.err( 4925): at com.money.manager.ex.utils.DateUtils.getDateFromString(DateUtils.java:68)
W/System.err( 4925): at com.money.manager.ex.search.SearchFragment.assembleWhereClause(SearchFragment.java:363)
W/System.err( 4925): at com.money.manager.ex.search.SearchFragment.executeSearch(SearchFragment.java:289)
W/System.err( 4925): at com.money.manager.ex.search.SearchFragment.handleSearchRequest(SearchFragment.java:417)
W/System.err( 4925): at com.money.manager.ex.search.SearchActivity.onFragmentViewCreated(SearchActivity.java:149)
W/System.err( 4925): at com.money.manager.ex.search.SearchFragment.onCreateView(SearchFragment.java:222)

**Comment by MisterY** [comment]
already fixed
