### ISSUE TITLE
Exception in Asset Allocation

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#604]
Version: 3.0.2
Build: 740

************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:142)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.ClassCastException: java.lang.Object[] cannot be cast to java.lang.String[]
at com.money.manager.ex.servicelayer.AssetAllocationService.loadStocks(AssetAllocationService.java:360)
at com.money.manager.ex.servicelayer.AssetAllocationService.loadStocks(AssetAllocationService.java:328)
at com.money.manager.ex.servicelayer.AssetAllocationService.loadAssetAllocation(AssetAllocationService.java:122)
at com.money.manager.ex.servicelayer.AssetAllocationService.loadAssetAllocation(AssetAllocationService.java:100)
at com.money.manager.ex.assetallocation.AssetAllocationLoader.loadInBackground(AssetAllocationLoader.java:49)
at com.money.manager.ex.assetallocation.AssetAllocationLoader.loadInBackground(AssetAllocationLoader.java:33)
at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:296)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:54)
at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:42)
at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:128)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 3 more

************ DEVICE INFORMATION ***********
Brand: google
Device: mako
Model: Nexus 4
Id: LMY47V
Product: occam

************ FIRMWARE ************
SDK: 22
Release: 5.1.1
Incremental: 1836172

**Comment by MisterY** [comment]
This seems to be caused by the Queryable library so I'm removing it.
