### ISSUE TITLE
Crash after prompting for permissions on Android 6

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#608]
When prompting for the storage access permissions, the activity loses focus and saves the instance state. This happens during the initialization so no fragments are shown. After returning from the confirmation dialog, the app crashes when trying to display the fragments.

************ APP DETAILS ************

Version: 3.1.0
Build: 742

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=2, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.money.manager.ex/com.money.manager.ex.home.MainActivity}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
at android.app.ActivityThread.-wrap16(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1500)
at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1518)
at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:613)
at com.money.manager.ex.home.MainActivity.displayDefaultFragment(MainActivity.java:586)
at com.money.manager.ex.home.MainActivity.initializeDatabaseAccess(MainActivity.java:630)
at com.money.manager.ex.home.MainActivity.initialize(MainActivity.java:620)
at com.money.manager.ex.home.MainActivity.onRequestPermissionsResult(MainActivity.java:490)
at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6553)
at android.app.Activity.dispatchActivityResult(Activity.java:6432)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
... 9 more

**Comment by diogocp** [comment]
Still seeing this issue

************ APP DETAILS ************

Version: 2015.12.24
Build: 753

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.money.manager.ex/com.money.manager.ex.home.MainActivity}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.app.ActivityThread.deliverResults(ActivityThread.java:3743)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:3786)
at android.app.ActivityThread.-wrap16(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5466)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1489)
at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1507)
at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:613)
at com.money.manager.ex.home.MainActivity.originalShowFragment(MainActivity.java:1120)
at com.money.manager.ex.home.MainActivity.initializeDatabaseAccess(MainActivity.java:625)
at com.money.manager.ex.home.MainActivity.initialize(MainActivity.java:613)
at com.money.manager.ex.home.MainActivity.onRequestPermissionsResult(MainActivity.java:412)
at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6582)
at android.app.Activity.dispatchActivityResult(Activity.java:6460)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3739)
... 9 more

************ DEVICE INFORMATION ***********
Brand: google
Device: mako
Model: Nexus 4
Id: MMB29M
Product: occam

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: ec79fb7c16

**Comment by MisterY** [comment]
Yep, thanks. The initialization flow is now not in correct order after prompting for permissions.
The best option would be to move permissions request to the Tutorial. That way the initialization of the Main activity would remain as before.
