### ISSUE TITLE
App crashes after prompting for permissions on Android 6/M

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#613]
************ FEEDBACK ************

An error occured when attempted to open the app.

************ APP DETAILS ************

Version: 3.1.2
Build: 744

************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1500)
at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1518)
at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:613)
at com.money.manager.ex.home.MainActivity$1.run(MainActivity.java:594)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:155)
at android.app.ActivityThread.main(ActivityThread.java:5511)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
at dalvik.system.NativeStart.main(Native Method)

**Comment by MisterY** [comment]
Can't reproduce: does not happen in the emulator.
