### ISSUE TITLE
Exception in the settings

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#636]
************ APP DETAILS ************

Version: 2016.01.12
Build: 755

************ CAUSE OF ERROR ************

java.lang.NullPointerException
at com.money.manager.ex.settings.SettingsBase.<init>(SettingsBase.java:32)
at com.money.manager.ex.settings.AppSettings.<init>(AppSettings.java:31)
at com.money.manager.ex.account.AccountTransactionListFragment.selectCurrentPeriod(AccountTransactionListFragment.java:762)
at com.money.manager.ex.account.AccountTransactionListFragment.onPrepareOptionsMenu(AccountTransactionListFragment.java:269)
at android.support.v4.app.Fragment.performPrepareOptionsMenu(Fragment.java:2058)
at android.support.v4.app.FragmentManagerImpl.dispatchPrepareOptionsMenu(FragmentManager.java:2145)
at android.support.v4.app.FragmentController.dispatchPrepareOptionsMenu(FragmentController.java:282)
at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:477)
at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:90)
at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onPreparePanel(AppCompatDelegateImplBase.java:268)
at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:90)
at android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:550)
at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:443)
at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:60)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4867)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
at dalvik.system.NativeStart.main(Native Method)

************ DEVICE INFORMATION ***********
Brand: samsung
Device: skomer
Model: GT-S7710
Id: JZO54K
Product: skomerxx

************ FIRMWARE ************
SDK: 16
Release: 4.1.2
Incremental: S7710XXAND2

**Comment by MisterY** [comment]
GetActivity() returned null in this case.

**Comment by MisterY** [comment]
Not occurring any longer.
