### ISSUE TITLE
Reports throw Unexpected Error

### ISSUE THREAD

**Issue by yoander** [moneymanagerex/android-money-manager-ex#666]
I appreciate a lot the job done by Android MoneyManagerEx team but I think it has a very fast release model due to this some important bugs are introduced with new versions as describe bellow.

I think is better a slower release model in pro of stability. Thanks

Any Report  throw Unexpected Error tested on Android 5.0 Samsung Galaxy S5

Here the log:

************ FEEDBACK ************

Please tell us what happened. Thank you!

************ APP DETAILS ************

Version: 2016.01.21
Build: 762

************ CAUSE OF ERROR ************

android.content.res.Resources$NotFoundException: Resource ID #0xffcc0000
at android.content.res.Resources.getValue(Resources.java:2333)
at android.content.res.Resources.getColor(Resources.java:1987)
at android.support.v4.content.ContextCompat.getColor(ContextCompat.java:368)
at com.money.manager.ex.reports.CategoriesReportAdapter.bindView(CategoriesReportAdapter.java:76)
at android.support.v4.widget.CursorAdapter.getView(CursorAdapter.java:256)
at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:232)
at android.widget.AbsListView.obtainView(AbsListView.java:2842)
at android.widget.ListView.makeAndAddView(ListView.java:1884)
at android.widget.ListView.fillDown(ListView.java:713)
at android.widget.ListView.fillFromTop(ListView.java:779)
at android.widget.ListView.layoutChildren(ListView.java:1679)
at android.widget.AbsListView.onLayout(AbsListView.java:2632)
at android.view.View.layout(View.java:16550)
at android.view.ViewGroup.layout(ViewGroup.java:5303)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
at android.view.View.layout(View.java:16550)
at android.view.ViewGroup.layout(ViewGroup.java:5303)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
at android.view.View.layout(View.java:16550)
at android.view.ViewGroup.layout(ViewGroup.java:5303)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2102)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1956)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1865)
at android.view.View.layout(View.java:16550)
at android.view.ViewGroup.layout(ViewGroup.java:5303)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2102)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1956)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1865)
at android.view.View.layout(View.java:16550)
at android.view.ViewGroup.layout(ViewGroup.java:5303)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
at android.view.View.layout(View.java:16550)
at android.view.ViewGroup.layout(ViewGroup.java:5303)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
at android.view.View.layout(View.java:16550)
at android.view.ViewGroup.layout(ViewGroup.java:5303)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
at android.view.View.layout(View.java:16550)
at android.view.ViewGroup.layout(ViewGroup.java:5303)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2102)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1956)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1865)
at android.view.View.layout(View.java:16550)
at android.view.ViewGroup.layout(ViewGroup.java:5303)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
at android.view.View.layout(View.java:16550)
at android.view.ViewGroup.layout(ViewGroup.java:5303)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2308)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2021)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1180)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6558)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
at android.view.Choreographer.doCallbacks(Choreographer.java:590)
at android.view.Choreographer.doFrame(Choreographer.java:560)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5832)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

************ DEVICE INFORMATION ***********
Brand: samsung
Device: k3g
Model: SM-G900H
Id: LRX21T
Product: k3gxx

************ FIRMWARE ************
SDK: 21
Release: 5.0
Incremental: G900HXXU1BOL1

**Comment by MisterY** [comment]
This is an unfortunate consequence of following up with the API method deprecation. The new Android API has a different method for getting colors from attributes. Hence the methods were migrated in order to avoid the situation where they don't work any longer in the new Android versions.

[More info](http://stackoverflow.com/questions/31590714/getcolorint-id-deprecated-on-android-6-0-marshmallow-api-23)

The issue will be corrected in the upcoming release.
