### ISSUE TITLE
Exception in Beta version

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#690]
************ APP DETAILS ************

Version: Beta
Build: 767

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method &#39;int com.money.manager.ex.recurring.transactions.Recurrence.ordinal()&#39; on a null object reference
at com.money.manager.ex.servicelayer.RecurringTransactionService.moveNextOccurrence(RecurringTransactionService.java:170)
at com.money.manager.ex.transactions.EditCheckingTransactionActivity.saveData(EditCheckingTransactionActivity.java:637)
at com.money.manager.ex.transactions.EditCheckingTransactionActivity.onActionDoneClick(EditCheckingTransactionActivity.java:178)
at com.money.manager.ex.common.BaseFragmentActivity$2.onClick(BaseFragmentActivity.java:161)
at android.view.View.performClick(View.java:5254)
at android.view.View$PerformClick.run(View.java:21203)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6897)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by MisterY** [comment]
Seems like junk data. The number for type of recurrence was not found.
