### ISSUE TITLE
Can't instantiate font icon

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#731]
************ APP DETAILS ************

Version: 2016.03.02
Build: 775

************ CAUSE OF ERROR ************

java.lang.NullPointerException
        at com.shamanland.fonticon.FontIconDrawable.inflate(FontIconDrawable.java:49)
        at com.money.manager.ex.account.AccountTransactionListFragment.initTransactionStatusMenu(AccountTransactionListFragment.java:492)
        at com.money.manager.ex.account.AccountTransactionListFragment.onCreateOptionsMenu(AccountTransactionListFragment.java:232)
        at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:2044)
        at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:2114)
        at android.support.v4.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:270)
        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:299)
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:241)
        at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
        at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:443)
        at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:60)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5314)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:862)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:678)
        at dalvik.system.NativeStart.main(Native Method)

************ DEVICE INFORMATION ***********
Brand: Huawei
Device: hwmt7
Model: HUAWEI MT7-L09
Id: HuaweiMT7-L09
Product: MT7-L09

************ FIRMWARE ************
SDK: 19
Release: 4.4.2
Incremental: C00B120SP04

**Comment by MisterY** [comment]
This is probably because during initialization of the menu, there is still no parent Activity assigned.

Ref: http://stackoverflow.com/questions/6215239/getactivity-returns-null-in-fragment-function

Will try using Context.
