### ISSUE TITLE
Exception caused by Joda Time during DST transition

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#748]
************ APP DETAILS ************

Version: 2016.03.18
Build: 791

************ CAUSE OF ERROR ************

org.joda.time.IllegalFieldValueException: Value 0 for hourOfDay is not supported: Illegal instant due to time zone offset transition (daylight savings time 'gap'): 2016-03-27T00:17:15.898 (Asia/Beirut)
at org.joda.time.chrono.ZonedChronology$ZonedDateTimeField.set(ZonedChronology.java:500)
at org.joda.time.DateTime.withHourOfDay(DateTime.java:1815)
at com.money.manager.ex.utils.MyDateTimeUtils.today(MyDateTimeUtils.java:42)
at com.money.manager.ex.utils.MyDateTimeUtils.getDateRangeForPeriod(MyDateTimeUtils.java:135)
at com.money.manager.ex.utils.MyDateTimeUtils.getDateRangeForPeriod(MyDateTimeUtils.java:115)
at com.money.manager.ex.account.AccountTransactionListFragment.onCreate(AccountTransactionListFragment.java:147)
at android.support.v4.app.Fragment.performCreate(Fragment.java:1951)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1029)
at android.support.v4.app.BackStackRecord.ensureFragmentsAreInitialized(BackStackRecord.java:1077)
at android.support.v4.app.BackStackRecord.beginTransition(BackStackRecord.java:1032)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:658)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: org.joda.time.IllegalInstantException: Illegal instant due to time zone offset transition (daylight savings time 'gap'): 2016-03-27T00:17:15.898 (Asia/Beirut)
at org.joda.time.chrono.ZonedChronology$ZonedDateTimeField.set(ZonedChronology.java:499)
... 19 more

************ DEVICE INFORMATION ***********
Brand: google
Device: hammerhead
Model: Nexus 5
Id: MMB29V
Product: hammerhead

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: 2554798

**Comment by MisterY** [comment]
This happens due to parsing the "non-existing" time during the DST transition, when the clock is moved forward, hence losing one hour. This one hour is treated as invalid DateTime value.

References:
- [SO](http://stackoverflow.com/questions/26162702/cannot-parse-datetime-illegal-instant-due-to-time-zone-offset-transition-euro)
