### ISSUE TITLE
Exception linking Dropbox

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#749]
************ APP DETAILS ************

Version: 2016.03.31
Build: 802

************ CAUSE OF ERROR ************

android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:575)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
	at android.app.Dialog.show(Dialog.java:319)
	at android.app.AlertDialog$Builder.show(AlertDialog.java:1112)
	at com.dropbox.client2.android.AuthActivity.checkAppBeforeAuth(AuthActivity.java:284)
	at com.dropbox.client2.android.AndroidAuthSession.startOAuth2Authentication(AndroidAuthSession.java:174)
	at com.dropbox.client2.android.AndroidAuthSession.startOAuth2Authentication(AndroidAuthSession.java:143)
	at com.dropbox.client2.android.AndroidAuthSession.startOAuth2Authentication(AndroidAuthSession.java:116)
	at com.money.manager.ex.dropbox.DropboxHelper.logIn(DropboxHelper.java:369)
	at com.money.manager.ex.settings.DropboxSettingsFragment$2.onPreferenceClick(DropboxSettingsFragment.java:174)
	at android.preference.Preference.performClick(Preference.java:996)
	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
	at android.widget.AbsListView$3.run(AbsListView.java:3903)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

************ DEVICE INFORMATION ***********
Brand: google
Device: flo
Model: Nexus 7
Id: MHC19J
Product: razor

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: 3f4ed30132

**Comment by MisterY** [comment]
This can be caused by the dialog shown using application context.
[Reference](http://stackoverflow.com/questions/7933206/android-unable-to-add-window-token-null-is-not-for-an-application-exception)
