### ISSUE TITLE
Force close when saving a new transaction or account with missing mandatory fields

### ISSUE THREAD

**Issue by prannou** [moneymanagerex/android-money-manager-ex#76]
The application crash when saving a transaction with missing mandatory field : for exemple saving an account with no name or a transaction with no payee.

I have the following stacktrace : com.afollestad.materialdialogs.MaterialDialog$DialogException: Bad window token, you cannot show a dialog before an Activity is created or after it's hidden.
            at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:1546)
            at com.money.manager.ex.CheckingAccountActivity.validateData(CheckingAccountActivity.java:1037)
            at com.money.manager.ex.CheckingAccountActivity.updateData(CheckingAccountActivity.java:1065)
            at com.money.manager.ex.CheckingAccountActivity.onActionDoneClick(CheckingAccountActivity.java:768)
            at com.money.manager.ex.fragment.BaseFragmentActivity$4.onClick(BaseFragmentActivity.java:159)
            at android.view.View.performClick(View.java:4756)
            at android.view.View$PerformClick.run(View.java:19749)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by AlessandroLazzari** [comment]
Hello, I am aware of the bug. In the first beta will be fixed.

2015-03-27 21:58 GMT+01:00 prannou <notifications@github.com>:
