### ISSUE TITLE
Unhandled Exception: Parsing DST transition date for America/Havana TZ

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#761]
************ APP DETAILS ************

Version: 2016.04.02
Build: 808

************ CAUSE OF ERROR ************

org.joda.time.IllegalInstantException: Cannot parse "2016-03-13": Illegal instant due to time zone offset transition (America/Havana)
at org.joda.time.format.DateTimeParserBucket.computeMillis(DateTimeParserBucket.java:471)
at org.joda.time.format.DateTimeParserBucket.computeMillis(DateTimeParserBucket.java:411)
at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:928)
at com.money.manager.ex.adapter.AllDataAdapter.bindView(AllDataAdapter.java:153)
at android.support.v4.widget.CursorAdapter.getView(CursorAdapter.java:256)
at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:232)
at android.widget.AbsListView.obtainView(AbsListView.java:2828)
at android.widget.ListView.makeAndAddView(ListView.java:1902)
at android.widget.ListView.fillDown(ListView.java:713)
at android.widget.ListView.fillGap(ListView.java:677)
at android.widget.AbsListView.trackMotionScroll(AbsListView.java:7054)
at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:6492)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
at android.view.Choreographer.doCallbacks(Choreographer.java:590)
at android.view.Choreographer.doFrame(Choreographer.java:559)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6126)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

************ DEVICE INFORMATION ***********
Brand: samsung
Device: viennalte
Model: SM-P905
Id: LRX22G
Product: viennaltexx

************ FIRMWARE ************
SDK: 21
Release: 5.0.2
Incremental: P905XXUABOG1

**Comment by MisterY** [comment]
Background info: [here](https://jira.atlassian.com/browse/JRA-22582)
The time zone America/Havana transitions to DST on midnight, hence the value 2016-03-13 is considered illegal.
