### ISSUE TITLE
Unhandled Exception: Account not found 0

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#765]
************ APP DETAILS ************

Version: 2016.04.02
Build: 811

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.money.manager.ex/com.money.manager.ex.transactions.EditCheckingTransactionActivity}: java.lang.IllegalArgumentException: Account not found 0
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2375)
at android.app.ActivityThread.access$900(ActivityThread.java:164)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1268)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:157)
at android.app.ActivityThread.main(ActivityThread.java:5377)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: Account not found 0
at com.money.manager.ex.datalayer.AccountRepository.loadCurrencyIdFor(AccountRepository.java:136)
at com.money.manager.ex.transactions.EditTransactionCommonFunctions.getAccountCurrencyId(EditTransactionCommonFunctions.java:270)
at com.money.manager.ex.transactions.EditTransactionCommonFunctions.getDestinationCurrencyId(EditTransactionCommonFunctions.java:293)
at com.money.manager.ex.transactions.EditTransactionCommonFunctions.displayAmountTo(EditTransactionCommonFunctions.java:1304)
at com.money.manager.ex.transactions.EditTransactionCommonFunctions.initAmountSelectors(EditTransactionCommonFunctions.java:478)
at com.money.manager.ex.transactions.EditCheckingTransactionActivity.initializeInputControls(EditCheckingTransactionActivity.java:275)
at com.money.manager.ex.transactions.EditCheckingTransactionActivity.onCreate(EditCheckingTransactionActivity.java:109)
at android.app.Activity.performCreate(Activity.java:5433)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2281)
... 11 more

************ DEVICE INFORMATION ***********
Brand: samsung
Device: v1awifi
Model: SM-P900
Id: KOT49H
Product: v1awifizs

************ FIRMWARE ************
SDK: 19
Release: 4.4.2
Incremental: P900ZSUANH2

**Comment by MisterY** [comment]
>Tried to edit closed down

Seems to happen on existing transactions.
