### ISSUE TITLE
Unhandled Exception: restoreInstanceState

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#769]
************ APP DETAILS ************

Version: 2016.04.02
Build: 811

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.money.manager.ex/com.money.manager.ex.transactions.EditCheckingTransactionActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2230)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2279)
at android.app.ActivityThread.access$800(ActivityThread.java:143)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1242)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5124)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:613)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.money.manager.ex.transactions.EditCheckingTransactionActivity.restoreInstanceState(EditCheckingTransactionActivity.java:519)
at com.money.manager.ex.transactions.EditCheckingTransactionActivity.onCreate(EditCheckingTransactionActivity.java:91)
at android.app.Activity.performCreate(Activity.java:5241)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2194)
... 11 more

************ DEVICE INFORMATION ***********
Brand: Sony
Device: D5103
Model: D5103
Id: 18.1.A.2.25
Product: D5103

************ FIRMWARE ************
SDK: 19
Release: 4.4.4
Incremental: 5vd_bw

**Comment by MisterY** [comment]
Unfortunately, can't reproduce. Users report this happening simply by opening Payee selector from an account transaction edit screen.
