### ISSUE TITLE
Unhandled Exception: adding/removing Favourite flag on account

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#784]
Was trying to make a newly created account visible in the right hand pane. Account was initially visible but I had somehow managed to hide it.

Tried to remove 'favorite' flag then replace it to see it that would work. Removed flag ok, but when I was trying to edit the account to replace the flag it crashed.

************ APP DETAILS ************

Version: 2016.02.02
Build: 766

************ CAUSE OF ERROR ************

java.lang.ClassCastException: android.widget.ExpandableListView$ExpandableListContextMenuInfo cannot be cast to android.widget.AdapterView$AdapterContextMenuInfo
at com.money.manager.ex.account.AccountListFragment.onContextItemSelected(AccountListFragment.java:111)
at android.support.v4.app.Fragment.performContextItemSelected(Fragment.java:2085)
at android.support.v4.app.FragmentManagerImpl.dispatchContextItemSelected(FragmentManager.java:2173)
at android.support.v4.app.FragmentController.dispatchContextItemSelected(FragmentController.java:308)
at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:370)
at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:147)
at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
at com.android.internal.policy.impl.PhoneWindow$DialogMenuCallback.onMenuItemSelected(PhoneWindow.java:5309)
at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:800)
at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:155)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:953)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:943)
at com.android.internal.view.menu.MenuDialogHelper.onClick(MenuDialogHelper.java:172)
at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1046)
at android.widget.AdapterView.performItemClick(AdapterView.java:334)
at android.widget.AbsListView.performItemClick(AbsListView.java:1536)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3683)
at android.widget.AbsListView$3.run(AbsListView.java:5604)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6145)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

************ DEVICE INFORMATION ***********
Brand: samsung
Device: gts28wifi
Model: SM-T710
Id: LRX22G
Product: gts28wifixx

************ FIRMWARE ************
SDK: 21
Release: 5.0.2
Incremental: T710XXU2AOJ4

**Comment by MisterY** [comment]
There has been so many changes since then. Can't reproduce this.
