### ISSUE TITLE
Handle error on update from sync service

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#871]
E/ContextImpl( 9350): Error uploading database file: ServiceCode Error in function uploadOverwrite at 13
D/OpenGLRenderer( 9350): prepareDirty (0.00, 0.00, 684.00, 192.00) opaque 0 <0x62c3b688>
D/OpenGLRenderer( 9350): clear (0.00, 192 - 192.00 = 0.00, 684.00 - 0.00 = 684.00, 192.00 - 0.00 = 192.00) opaque 0 <0x62c3b688>
D/OpenGLRenderer( 9350): finish <0x62c3b688>
W/System.err( 9350): java.lang.RuntimeException: ServiceCode Error in function uploadOverwrite at 13
W/System.err( 9350): 	at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:108)
W/System.err( 9350): 	at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:42)
W/System.err( 9350): 	at com.cloudrail.si.services.GoogleDrive.upload(GoogleDrive.java:972)
W/System.err( 9350): 	at com.money.manager.ex.sync.SyncManager.upload(SyncManager.java:515)
W/System.err( 9350): 	at com.money.manager.ex.sync.SyncService.triggerUpload(SyncService.java:246)
W/System.err( 9350): 	at com.money.manager.ex.sync.SyncService.triggerSync(SyncService.java:273)
W/System.err( 9350): 	at com.money.manager.ex.sync.SyncService.onHandleIntent(SyncService.java:129)
W/System.err( 9350): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
W/System.err( 9350): 	at android.os.Handler.dispatchMessage(Handler.java:110)
W/System.err( 9350): 	at android.os.Looper.loop(Looper.java:193)
W/System.err( 9350): 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err( 9350): Caused by: java.lang.ClassCastException: android.app.ContextImpl cannot be cast to android.app.Activity
W/System.err( 9350): 	at com.cloudrail.si.servicecode.commands.GetMimeType.init(GetMimeType.java:44)
W/System.err( 9350): 	at com.cloudrail.si.servicecode.commands.GetMimeType.execute(GetMimeType.java:34)
W/System.err( 9350): 	at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:84)
W/System.err( 9350): 	... 10 more
V/PhoneWindow( 9350): DecorView setVisiblity: visibility = 8 ,Parent =ViewRoot{426905d8 com.money.manager.ex.beta/com.money.manager.ex.home.MainActivity,ident = 6}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{42532498 G.E..... R.....I. 0,0-684,192}
D/OpenGLRenderer( 9350): Flushing caches (mode 0)
D/GraphicBuffer( 9350): close handle(0x675e4c30) (w:688 h:192 f:1)
D/GraphicBuffer( 9350): close handle(0x641549b0) (w:688 h:192 f:1)
D/GraphicBuffer( 9350): close handle(0x63a77960) (w:688 h:192 f:1)
D/GraphicBuffer( 9350): close handle(0x654b3ac0) (w:688 h:192 f:1)
D/ActivityThread( 9350): SVC-Destroying service: com.money.manager.ex.sync.SyncService@427284d0

**Comment by MisterY** [comment]
This seems like the old version.
