### ISSUE TITLE
Unhandled Exception: Calling startActivity() from outside of an Activity

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#872]
************ APP DETAILS ************
Version: 2016.07.13
Build: 854

************ FIRMWARE ************
SDK: 19
Release: 5.0
Incremental: eng.jenkins.1402738150

************ CAUSE OF ERROR ************
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
at android.app.ContextImpl.startActivity(ContextImpl.java)
at android.app.ContextImpl.startActivity(ContextImpl.java)
at com.cloudrail.si.servicecode.commands.AwaitCodeRedirect$1.run(AwaitCodeRedirect.java:81)
at android.os.Handler.handleCallback(Handler.java)
at android.os.Handler.dispatchMessage(Handler.java)
at android.os.Looper.loop(Looper.java)
at android.app.ActivityThread.main(ActivityThread.java)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
at dalvik.system.NativeStart.main(Native Method)

# Reported Solutions
The solutions below were reported by users who claim that after the action, the sync started working. Usually one of the actions below was the final one.

- reboot the device
- uninstall and reinstall the app
- delete extra files in Dropbox
- use a different service
- set the Provider in the synchronization settings
-  clear the app cache and data

**Comment by MisterY** [comment]
A user reports that he had multiple files in the Dropbox folder, that begin with the same name (backups). After deleting these files, the sync worked flawlessly.

**Comment by MisterY** [comment]
Seems to have been resolved with the new build. The issue is in the context. When the scheduled sync downloads the database, it also tries to restart the Main Activity. However, this is where the context is wrong. This has been adjusted to not restart the app if the event was not triggered from an Activity.

**Comment by MisterY** [comment]
Several users confirm that the issue disappeared after they uninstalled and reinstalled the app.

**Comment by MisterY** [comment]
Based on the results, this has been resolved by the new version of the CloudRail library.
