### ISSUE TITLE
Error on GoogleDrive upload

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#875]
07-15 01:18:13.264 29122 31200 E ContextImpl: version: 2016.07.14: Error uploading database file: ServiceCode Error in function uploadOverwrite at 13
07-15 01:18:13.264 29122 31200 W System.err: java.lang.RuntimeException: ServiceCode Error in function uploadOverwrite at 13
07-15 01:18:13.264 29122 31200 W System.err: at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:108)
07-15 01:18:13.264 29122 31200 W System.err: at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:42)
07-15 01:18:13.264 29122 31200 W System.err: at com.cloudrail.si.services.GoogleDrive.upload(GoogleDrive.java:972)
07-15 01:18:13.264 29122 31200 W System.err: at com.money.manager.ex.sync.SyncManager.upload(SyncManager.java:523)
07-15 01:18:13.264 29122 31200 W System.err: at com.money.manager.ex.sync.SyncService.triggerUpload(SyncService.java:246)
07-15 01:18:13.264 29122 31200 W System.err: at com.money.manager.ex.sync.SyncService.onHandleIntent(SyncService.java:125)
07-15 01:18:13.264 29122 31200 W System.err: at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
07-15 01:18:13.264 29122 31200 W System.err: at android.os.Handler.dispatchMessage(Handler.java:102)
07-15 01:18:13.264 29122 31200 W System.err: at android.os.Looper.loop(Looper.java:158)
07-15 01:18:13.264 29122 31200 W System.err: at android.os.HandlerThread.run(HandlerThread.java:61)
07-15 01:18:13.264 29122 31200 W System.err: Caused by: java.lang.ClassCastException: android.app.ContextImpl cannot be cast to android.app.Activity
07-15 01:18:13.264 29122 31200 W System.err: at com.cloudrail.si.servicecode.commands.GetMimeType.init(GetMimeType.java:44)
07-15 01:18:13.264 29122 31200 W System.err: at com.cloudrail.si.servicecode.commands.GetMimeType.execute(GetMimeType.java:34)
07-15 01:18:13.264 29122 31200 W System.err: at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:84)
07-15 01:18:13.264 29122 31200 W System.err: ... 9 more

**Comment by MisterY** [comment]
Resolved in the new version of CloudRail library.
