### ISSUE TITLE
Dropbox login fails

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#877]
************ APP DETAILS ************
Version: 2016.07.14
Build: 857

************ FIRMWARE ************
SDK: 19
Release: 4.4.2
Incremental: eng.huangnan.1401964094

************ CAUSE OF ERROR ************
com.cloudrail.si.exceptions.AuthenticationException: Authentication was cancelled
at com.cloudrail.si.services.Dropbox.login(Dropbox.java:905)
at com.money.manager.ex.sync.SyncManager$2.run(SyncManager.java:329)
at java.lang.Thread.run(Thread.java:841)

**Comment by MisterY** [comment]
Can't do much about this at the moment.
