### ISSUE TITLE
Message "Error getting default system currency for" appearing on "Home" screen

### ISSUE THREAD

**Issue by Athanagorn** [moneymanagerex/android-money-manager-ex#904]
Hello,

Every time I go to the "Home" screen ("Accueil" in french) and on some others screen too, I got the message "Error getting default system currency for" that appears at the bottom of the screen.
<img src="https://cloud.githubusercontent.com/assets/20598877/17060053/7dfadf60-5028-11e6-9b03-58ededadaac9.png" width="200px" />

I downloaded the app from the app store today for the first time, version 2016.07.18.867.
I have a OnePlus 2 (ONE A2003) with Android 6.0.1

Might be related to https://github.com/moneymanagerex/android-money-manager-ex/issues/841 which is closed as  solved?

**Comment by MisterY** [comment]
Thanks for pointing this out. As a matter of fact, this is the second-highest ranked issue. Fortunately it does not crash the app but is annoying nonetheless. Below is the most common stack trace:
```
Non-fatal Exception: java.lang.IllegalArgumentException: Unsupported ISO 3166 country: it
       at java.util.Currency.getInstance(Currency.java:84)
       at com.money.manager.ex.currency.CurrencyService.getSystemDefaultCurrency(CurrencyService.java:414)
       at com.money.manager.ex.currency.CurrencyService.getBaseCurrencyId(CurrencyService.java:227)
       at com.money.manager.ex.home.HomeFragment.onLoadFinished(HomeFragment.java:324)
       at com.money.manager.ex.home.HomeFragment.onLoadFinished(HomeFragment.java:101)
       at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:479)
       at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:447)
       at android.support.v4.content.Loader.deliverResult(Loader.java:126)
       at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:105)
       at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:37)
       at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:249)
       at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:77)
       at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:466)
       at android.support.v4.content.ModernAsyncTask.access$400(ModernAsyncTask.java:48)
       at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:483)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5451)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Some more info on the cause - [here](http://stackoverflow.com/questions/13316719/how-to-create-currency-instance-with-non-iso-3166-country-like-en-uk). It seems that the ISO language codes do not match the country codes for currencies.
[ISO3166](http://userpage.chemie.fu-berlin.de/diverse/doc/ISO_3166.html)

Since I see IT there, it is possible that this is just a matter of capitalizing the country code. Will try that approach.

**Comment by MisterY** [comment]
Oh, clarification. In this particular case, the screenshot shows that there is no country code at all.
The message I'm getting in the error logs is "Unsupported ISO 3166 country: it". 
So, capitalization might solve the "it" problem by providing "IT" to the system. Hopefully.
In your case I might need to specifically handle the case where no locale is returned. It would be very good to have someone debug on such a device since all the devices I've tried this on work as expected.

What is your language setting in the app, and what is the language setting for the system?

**Comment by Athanagorn** [comment]
My language setting for the system is "Français (France)"
My language setting for the app is "Français".
Note that I got the same error if I select "Default" as language for the app, and even if I select "English".
I also changed the language setting for my phone to "English (United Kingdom)" and I still have the message.

**Comment by MisterY** [comment]
Just as an info, could you tell me if the message changes? I'm interested in what country code is returned at the end of the message (getting the currency info *for* ___).
I'm reading more about how to handle this. The exception messages that are collected include it, de, es, fr, pt-BR. Pretty much everything. The Java Currency does not recognise the code.
And this is correct, since the country code should be capitalized.
In any case, this was supposed to make it easier for users and select the default currency. I will handle this specific exception and just provide a default currency value in that case, most probably.

**Comment by Athanagorn** [comment]
The message is the same whatever the app language / system language

The trace for the english is:
```
07-22 16:50:54.140  5277  5277 W System.err: java.lang.IllegalArgumentException: Unsupported ISO 3166 country: en
07-22 16:50:54.141  5277  5277 W System.err: 	at java.util.Currency.getInstance(Currency.java:84)
07-22 16:50:54.141  5277  5277 W System.err: 	at com.money.manager.ex.currency.CurrencyService.getSystemDefaultCurrency(CurrencyService.java:414)
07-22 16:50:54.141  5277  5277 W System.err: 	at com.money.manager.ex.currency.CurrencyService.getBaseCurrencyId(CurrencyService.java:227)
07-22 16:50:54.141  5277  5277 W System.err: 	at com.money.manager.ex.currency.CurrencyService.getBaseCurrencyFormatted(CurrencyService.java:279)
07-22 16:50:54.141  5277  5277 W System.err: 	at com.money.manager.ex.home.HomeAccountsExpandableAdapter.getGroupView(HomeAccountsExpandableAdapter.java:139)
07-22 16:50:54.141  5277  5277 W System.err: 	at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:446)
07-22 16:50:54.141  5277  5277 W System.err: 	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
07-22 16:50:54.141  5277  5277 W System.err: 	at android.widget.AbsListView.obtainView(AbsListView.java:2348)
07-22 16:50:54.141  5277  5277 W System.err: 	at android.widget.ListView.makeAndAddView(ListView.java:1876)
07-22 16:50:54.141  5277  5277 W System.err: 	at android.widget.ListView.fillDown(ListView.java:702)
07-22 16:50:54.141  5277  5277 W System.err: 	at android.widget.ListView.fillFromTop(ListView.java:763)
07-22 16:50:54.141  5277  5277 W System.err: 	at android.widget.ListView.layoutChildren(ListView.java:1671)
07-22 16:50:54.141  5277  5277 W System.err: 	at android.widget.AbsListView.onLayout(AbsListView.java:2150)
07-22 16:50:54.141  5277  5277 W System.err: 	at android.view.View.layout(View.java:16692)
07-22 16:50:54.141  5277  5277 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5442)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.view.View.layout(View.java:16692)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5442)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.view.View.layout(View.java:16692)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5442)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.view.View.layout(View.java:16692)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5442)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.view.View.layout(View.java:16692)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5442)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.view.View.layout(View.java:16692)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5442)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.view.View.layout(View.java:16692)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5442)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.view.View.layout(View.java:16692)
07-22 16:50:54.142  5277  5277 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5442)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.view.View.layout(View.java:16692)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5442)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1191)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.view.View.layout(View.java:16692)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5442)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.view.View.layout(View.java:16692)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5442)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.view.View.layout(View.java:16692)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5442)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.view.View.layout(View.java:16692)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5442)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.view.View.layout(View.java:16692)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5442)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
07-22 16:50:54.143  5277  5277 W System.err: 	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2706)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.view.View.layout(View.java:16692)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5442)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2178)
07-22 16:50:54.143  5277  5277 W System.err: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1938)
07-22 16:50:54.144  5277  5277 W System.err: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1114)
07-22 16:50:54.144  5277  5277 W System.err: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6068)
07-22 16:50:54.144  5277  5277 W System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
07-22 16:50:54.144  5277  5277 W System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
07-22 16:50:54.144  5277  5277 W System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:606)
07-22 16:50:54.144  5277  5277 W System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
07-22 16:50:54.144  5277  5277 W System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
07-22 16:50:54.144  5277  5277 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-22 16:50:54.144  5277  5277 W System.err: 	at android.os.Looper.loop(Looper.java:152)
07-22 16:50:54.144  5277  5277 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5497)
07-22 16:50:54.144  5277  5277 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
07-22 16:50:54.144  5277  5277 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-22 16:50:54.144  5277  5277 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by MisterY** [comment]
Yes, the country code is missing in your default locale (?!). It is just returning the language code, not the country code. I'm not sure what is causing it. Definitely some issue with the system.
I will handle the issue specifically and publish a new beta version very soon.
Your other issue is that the default currency is still not set. As a workaround you can manually set the default currency in the General settings (it probably failed during the database creation).
However, note that setting this will prevent you from confirming on whether the issue was corrected in the upcoming Beta.

I'd recommend you install the beta build 871 in a couple of hours and please confirm if the message is gone. Then you should set the default currency in the settings. 
Thanks for the contribution!

**Comment by MisterY** [comment]
More info [here](https://code.google.com/p/android/issues/detail?id=2372). Although, the statements in that thread do not match what was said here, in our thread. Even though you have fr_FR, the Country Code is still empty and the Java Currency can not identify the currency for that.

**Comment by MisterY** [comment]
OK, the build has been published. Please give it an hour or so to show up.
I've added the build number to the What's New section. Look for 871.

**Comment by Athanagorn** [comment]
Ok, I can confirm that the annoying message is gone. I still get one message saying "error init database, currency" when creating a new database, but it's a oneshot

**Comment by MisterY** [comment]
Thank you for the confirmation! I will check the creation process, too.

**Comment by MisterY** [comment]
Improved for the upcoming version.
