### ISSUE TITLE
Unhandled Exception in Category list

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#908]
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at com.money.manager.ex.adapter.CategoryExpandableListAdapter.getGroupView(CategoryExpandableListAdapter.java:171)
       at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:446)
       at android.widget.AbsListView.obtainView(AbsListView.java:2474)
       at android.widget.ListView.makeAndAddView(ListView.java:1920)
       at android.widget.ListView.fillDown(ListView.java:717)
       at android.widget.ListView.fillFromTop(ListView.java:778)
       at android.widget.ListView.layoutChildren(ListView.java:1701)
       at android.widget.AbsListView.onLayout(AbsListView.java:2235)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
       at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2728)
       at android.view.View.layout(View.java:16953)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2558)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2261)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1327)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6816)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
       at android.view.Choreographer.doCallbacks(Choreographer.java:696)
       at android.view.Choreographer.doFrame(Choreographer.java:631)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5746)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:683)

**Comment by MisterY** [comment]
It is now handled but need to find it in the handled exceptions.
