### ISSUE TITLE
Exception on cloud network call

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#957]
JSON response is most often null when fetching metadata from the delayed or the scheduled sync service call.

```
08-17 22:19:58.667 22813-26892/com.money.manager.ex E/SyncManager: fetching remote file info
java.lang.RuntimeException: ServiceCode Error in function standardJSONRequest at 11
   at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:108)
   at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:42)
   at com.cloudrail.si.services.Dropbox.getMetadata(Dropbox.java:889)
   at com.money.manager.ex.sync.SyncManager.loadMetadata(SyncManager.java:355)
   at com.money.manager.ex.sync.SyncService.onHandleIntent(SyncService.java:85)
   at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
   at android.os.Handler.dispatchMessage(Handler.java:99)
   at android.os.Looper.loop(Looper.java:137)
   at android.os.HandlerThread.run(HandlerThread.java:60)
Caused by: java.lang.NullPointerException
   at com.cloudrail.si.servicecode.commands.http.RequestCall.execute(RequestCall.java:113)
   at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:84)
   at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:42) 
   at com.cloudrail.si.services.Dropbox.getMetadata(Dropbox.java:889) 
   at com.money.manager.ex.sync.SyncManager.loadMetadata(SyncManager.java:355) 
   at com.money.manager.ex.sync.SyncService.onHandleIntent(SyncService.java:85) 
   at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
   at android.os.Handler.dispatchMessage(Handler.java:99) 
   at android.os.Looper.loop(Looper.java:137) 
   at android.os.HandlerThread.run(HandlerThread.java:60) 
```

**Comment by MisterY** [comment]
See if #950 will fix this.

**Comment by MisterY** [comment]
Related issue: https://github.com/CloudRail/cloudrail-si-android-sdk/issues/32

**Comment by MisterY** [comment]
Test summary:

1.  case
  a. Running the app, 
  b. setting the sync interval, 
  c. editing data, 
  d. pressing Back to get back to the system
2. case, same as above
  e. removing the app from the recent apps list
3. case, same as 1,
  e. force stop from the App Info.

**Comment by MisterY** [comment]
The focus is now on the first scenario. Changing the data, going back to the system home.

**Comment by MisterY** [comment]
As a workaround, add one retry for getMetadata call. This should resolve the majority of issues.
