### ISSUE TITLE
Unhandled Exception: array ouf of bounds

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#978]
Add logging to trace the steps or the location where the exception happens? [See here](https://docs.fabric.io/android/crashlytics/enhanced-reports.html#custom-logging)
However, this is not caught and will probably need some feedback or a test case.

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at android.widget.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:164)
       at android.widget.ListView.dispatchDraw(ListView.java:3307)
       at android.widget.ExpandableListView.dispatchDraw(ExpandableListView.java:353)
       at android.view.View.draw(View.java:15125)
       at android.widget.AbsListView.draw(AbsListView.java:4110)
       at android.view.View.updateDisplayListIfDirty(View.java:14056)
       at android.view.View.getDisplayList(View.java:14079)
       at android.view.View.draw(View.java:14846)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.updateDisplayListIfDirty(View.java:14051)
       at android.view.View.getDisplayList(View.java:14079)
       at android.view.View.draw(View.java:14846)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.draw(View.java:15125)
       at android.view.View.updateDisplayListIfDirty(View.java:14056)
       at android.view.View.getDisplayList(View.java:14079)
       at android.view.View.draw(View.java:14846)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.draw(View.java:15125)
       at android.widget.FrameLayout.draw(FrameLayout.java:592)
       at android.view.View.updateDisplayListIfDirty(View.java:14056)
       at android.view.View.getDisplayList(View.java:14079)
       at android.view.View.draw(View.java:14846)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.draw(View.java:15125)
       at android.view.View.updateDisplayListIfDirty(View.java:14056)
       at android.view.View.getDisplayList(View.java:14079)
       at android.view.View.draw(View.java:14846)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.updateDisplayListIfDirty(View.java:14051)
       at android.view.View.getDisplayList(View.java:14079)
       at android.view.View.draw(View.java:14846)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.draw(View.java:15125)
       at android.view.View.updateDisplayListIfDirty(View.java:14056)
       at android.view.View.getDisplayList(View.java:14079)
       at android.view.View.draw(View.java:14846)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3210)
       at android.view.View.draw(View.java:15125)
       at android.view.View.updateDisplayListIfDirty(View.java:14056)
       at android.view.View.getDisplayList(View.java:14079)
       at android.view.View.draw(View.java:14846)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.draw(View.java:15125)
       at android.view.View.updateDisplayListIfDirty(View.java:14056)
       at android.view.View.getDisplayList(View.java:14079)
       at android.view.View.draw(View.java:14846)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
       at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1377)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.updateDisplayListIfDirty(View.java:14051)
       at android.view.View.getDisplayList(View.java:14079)
       at android.view.View.draw(View.java:14846)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.updateDisplayListIfDirty(View.java:14051)
       at android.view.View.getDisplayList(View.java:14079)
       at android.view.View.draw(View.java:14846)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.updateDisplayListIfDirty(View.java:14051)
       at android.view.View.getDisplayList(View.java:14079)
       at android.view.View.draw(View.java:14846)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.updateDisplayListIfDirty(View.java:14051)
       at android.view.View.getDisplayList(View.java:14079)
       at android.view.View.draw(View.java:14846)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.draw(View.java:15125)
       at android.view.View.updateDisplayListIfDirty(View.java:14056)
       at android.view.View.getDisplayList(View.java:14079)
       at android.view.View.draw(View.java:14846)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
       at android.view.View.draw(View.java:15125)
       at android.widget.FrameLayout.draw(FrameLayout.java:592)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2595)
       at android.view.View.updateDisplayListIfDirty(View.java:14056)
       at android.view.View.getDisplayList(View.java:14079)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:266)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:272)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:311)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2492)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2337)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1968)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:550)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5264)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
```

**Comment by MisterY** [comment]
Not showing up any longer?
